// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CraftArgs {
    pub recipe_id: u16,
}

impl From<CraftArgs> for super::Reducer {
    fn from(args: CraftArgs) -> Self {
        Self::Craft {
            recipe_id: args.recipe_id,
        }
    }
}

impl __sdk::InModule for CraftArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `craft`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait craft {
    /// Request that the remote module invoke the reducer `craft` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`craft:craft_then`] to run a callback after the reducer completes.
    fn craft(&self, recipe_id: u16) -> __sdk::Result<()> {
        self.craft_then(recipe_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `craft` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn craft_then(
        &self,
        recipe_id: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl craft for super::RemoteReducers {
    fn craft_then(
        &self,
        recipe_id: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CraftArgs { recipe_id }, callback)
    }
}
