// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Inventory {
    pub owner: __sdk::Identity,
    pub slots: String,
    pub selected: u8,
}

impl __sdk::InModule for Inventory {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Inventory`.
///
/// Provides typed access to columns for query building.
pub struct InventoryCols {
    pub owner: __sdk::__query_builder::Col<Inventory, __sdk::Identity>,
    pub slots: __sdk::__query_builder::Col<Inventory, String>,
    pub selected: __sdk::__query_builder::Col<Inventory, u8>,
}

impl __sdk::__query_builder::HasCols for Inventory {
    type Cols = InventoryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InventoryCols {
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            slots: __sdk::__query_builder::Col::new(table_name, "slots"),
            selected: __sdk::__query_builder::Col::new(table_name, "selected"),
        }
    }
}

/// Indexed column accessor struct for the table `Inventory`.
///
/// Provides typed access to indexed columns for query building.
pub struct InventoryIxCols {
    pub owner: __sdk::__query_builder::IxCol<Inventory, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Inventory {
    type IxCols = InventoryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InventoryIxCols {
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Inventory {}
