// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PickupLootArgs {
    pub loot_id: u64,
}

impl From<PickupLootArgs> for super::Reducer {
    fn from(args: PickupLootArgs) -> Self {
        Self::PickupLoot {
            loot_id: args.loot_id,
        }
    }
}

impl __sdk::InModule for PickupLootArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `pickup_loot`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait pickup_loot {
    /// Request that the remote module invoke the reducer `pickup_loot` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`pickup_loot:pickup_loot_then`] to run a callback after the reducer completes.
    fn pickup_loot(&self, loot_id: u64) -> __sdk::Result<()> {
        self.pickup_loot_then(loot_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `pickup_loot` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn pickup_loot_then(
        &self,
        loot_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl pickup_loot for super::RemoteReducers {
    fn pickup_loot_then(
        &self,
        loot_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PickupLootArgs { loot_id }, callback)
    }
}
