// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SelectSlotArgs {
    pub slot: u8,
}

impl From<SelectSlotArgs> for super::Reducer {
    fn from(args: SelectSlotArgs) -> Self {
        Self::SelectSlot { slot: args.slot }
    }
}

impl __sdk::InModule for SelectSlotArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `select_slot`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait select_slot {
    /// Request that the remote module invoke the reducer `select_slot` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`select_slot:select_slot_then`] to run a callback after the reducer completes.
    fn select_slot(&self, slot: u8) -> __sdk::Result<()> {
        self.select_slot_then(slot, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `select_slot` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn select_slot_then(
        &self,
        slot: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl select_slot for super::RemoteReducers {
    fn select_slot_then(
        &self,
        slot: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SelectSlotArgs { slot }, callback)
    }
}
