// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SwapSlotsArgs {
    pub a: u8,
    pub b: u8,
}

impl From<SwapSlotsArgs> for super::Reducer {
    fn from(args: SwapSlotsArgs) -> Self {
        Self::SwapSlots {
            a: args.a,
            b: args.b,
        }
    }
}

impl __sdk::InModule for SwapSlotsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `swap_slots`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait swap_slots {
    /// Request that the remote module invoke the reducer `swap_slots` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`swap_slots:swap_slots_then`] to run a callback after the reducer completes.
    fn swap_slots(&self, a: u8, b: u8) -> __sdk::Result<()> {
        self.swap_slots_then(a, b, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `swap_slots` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn swap_slots_then(
        &self,
        a: u8,
        b: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl swap_slots for super::RemoteReducers {
    fn swap_slots_then(
        &self,
        a: u8,
        b: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SwapSlotsArgs { a, b }, callback)
    }
}
