// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TransferStationArgs {
    pub station_id: u64,
    pub bag_slot: u8,
    pub st_slot: u8,
    pub to_station: bool,
}

impl From<TransferStationArgs> for super::Reducer {
    fn from(args: TransferStationArgs) -> Self {
        Self::TransferStation {
            station_id: args.station_id,
            bag_slot: args.bag_slot,
            st_slot: args.st_slot,
            to_station: args.to_station,
        }
    }
}

impl __sdk::InModule for TransferStationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `transfer_station`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait transfer_station {
    /// Request that the remote module invoke the reducer `transfer_station` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`transfer_station:transfer_station_then`] to run a callback after the reducer completes.
    fn transfer_station(
        &self,
        station_id: u64,
        bag_slot: u8,
        st_slot: u8,
        to_station: bool,
    ) -> __sdk::Result<()> {
        self.transfer_station_then(station_id, bag_slot, st_slot, to_station, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `transfer_station` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn transfer_station_then(
        &self,
        station_id: u64,
        bag_slot: u8,
        st_slot: u8,
        to_station: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl transfer_station for super::RemoteReducers {
    fn transfer_station_then(
        &self,
        station_id: u64,
        bag_slot: u8,
        st_slot: u8,
        to_station: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TransferStationArgs {
                station_id,
                bag_slot,
                st_slot,
                to_station,
            },
            callback,
        )
    }
}
