// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::world_loot_type::WorldLoot;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `world_loot`.
///
/// Obtain a handle from the [`WorldLootTableAccess::world_loot`] method on [`super::RemoteTables`],
/// like `ctx.db.world_loot()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_loot().on_insert(...)`.
pub struct WorldLootTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorldLoot>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `world_loot`.
pub struct WorldLootTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for WorldLootTableAccessor {
    type Row = WorldLoot;
    type Handle<'db> = WorldLootTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.world_loot()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `world_loot`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorldLootTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorldLootTableHandle`], which mediates access to the table `world_loot`.
    fn world_loot(&self) -> WorldLootTableHandle<'_>;
}

impl WorldLootTableAccess for super::RemoteTables {
    fn world_loot(&self) -> WorldLootTableHandle<'_> {
        WorldLootTableHandle {
            imp: self.imp.get_table::<WorldLoot>("world_loot"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorldLootInsertCallbackId(__sdk::CallbackId);
pub struct WorldLootDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for WorldLootTableHandle<'ctx> {
    type Row = WorldLoot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldLoot> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for WorldLootTableHandle<'ctx> {
    type Row = WorldLoot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldLoot> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorldLootInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldLootInsertCallbackId {
        WorldLootInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldLootInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorldLootDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldLootDeleteCallbackId {
        WorldLootDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldLootDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for WorldLootTableHandle<'ctx> {
    type InsertCallbackId = WorldLootInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldLootInsertCallbackId {
        WorldLootInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldLootInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for WorldLootTableHandle<'ctx> {
    type DeleteCallbackId = WorldLootDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldLootDeleteCallbackId {
        WorldLootDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldLootDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WorldLootUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorldLootTableHandle<'ctx> {
    type UpdateCallbackId = WorldLootUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldLootUpdateCallbackId {
        WorldLootUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldLootUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for WorldLootTableHandle<'ctx> {
    type UpdateCallbackId = WorldLootUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldLootUpdateCallbackId {
        WorldLootUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldLootUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `world_loot`,
/// which allows point queries on the field of the same name
/// via the [`WorldLootIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_loot().id().find(...)`.
pub struct WorldLootIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorldLoot, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorldLootTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `world_loot`.
    pub fn id(&self) -> WorldLootIdUnique<'ctx> {
        WorldLootIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorldLootIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<WorldLoot> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorldLoot>("world_loot");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WorldLoot>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorldLoot>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorldLoot`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait world_lootQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorldLoot`.
    fn world_loot(&self) -> __sdk::__query_builder::Table<WorldLoot>;
}

impl world_lootQueryTableAccess for __sdk::QueryTableAccessor {
    fn world_loot(&self) -> __sdk::__query_builder::Table<WorldLoot> {
        __sdk::__query_builder::Table::new("world_loot")
    }
}
