// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldLoot {
    pub id: u64,
    pub item_id: u16,
    pub count: u16,
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

impl __sdk::InModule for WorldLoot {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WorldLoot`.
///
/// Provides typed access to columns for query building.
pub struct WorldLootCols {
    pub id: __sdk::__query_builder::Col<WorldLoot, u64>,
    pub item_id: __sdk::__query_builder::Col<WorldLoot, u16>,
    pub count: __sdk::__query_builder::Col<WorldLoot, u16>,
    pub x: __sdk::__query_builder::Col<WorldLoot, f32>,
    pub y: __sdk::__query_builder::Col<WorldLoot, f32>,
    pub z: __sdk::__query_builder::Col<WorldLoot, f32>,
}

impl __sdk::__query_builder::HasCols for WorldLoot {
    type Cols = WorldLootCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WorldLootCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            item_id: __sdk::__query_builder::Col::new(table_name, "item_id"),
            count: __sdk::__query_builder::Col::new(table_name, "count"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
        }
    }
}

/// Indexed column accessor struct for the table `WorldLoot`.
///
/// Provides typed access to indexed columns for query building.
pub struct WorldLootIxCols {
    pub id: __sdk::__query_builder::IxCol<WorldLoot, u64>,
}

impl __sdk::__query_builder::HasIxCols for WorldLoot {
    type IxCols = WorldLootIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WorldLootIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WorldLoot {}
